---
title: "Efficacy of Transdiagnostic Cognitive-Behavioral Therapy for Assertiveness: A Randomized Controlled Trial"
runtitle: "Transdiagnostic CBT for Assertiveness"
author:
  - name: Tobias Hagberg
    affiliation: SU
  - name: Patrik Manhem
    affiliation: SU
  - name: Martin Oscarsson
    affiliation: SU
  - name: Fiona Michel
    affiliation: CCI
  - name: Gerhard Andersson
    affiliation: LU,KI
  - name: Per Carlbring
    email: per.carlbring@psychology.su.se
    correspondingauthor: true
    affiliation: SU
address:  
  - code: SU
    address: "Department of Psychology, Stockholm University, SE-106 91 Stockholm, Sweden"
  - code: KI
    address: "Department of Clinical Neuroscience, Karolinska Institutet, SE-171 77 Stockholm, Sweden"
  - code: LU
    address: "Department of Behavioural Sciences and Learning, Department of Biomedical and Clinical Sciences, Linkoping University, SE-581 83 Linkoping, Sweden"
  - code: CCI
    address: "Centre for Clinical Interventions, 223 James St, Northbridge WA 6003, Australia"
abstract: |
  `r readLines('abstract.Rmd', encoding = 'UTF-8')`
keywords: 
  - "assertiveness"
  - "assertive behavior"
  - "anxiety"
  - "depression"
  - "stress"
  - "avoidance"
date: "`r Sys.Date()`"
#https://www.elsevier.com/authors/policies-and-guidelines/documents/elsdoc-1.pdf
bibliography:
  - packages.bib
  - KSH.bib
  - DBT.bib
linenumbers: true
numbersections: false
#csl: ./apa.csl
csl: ./elsevier-harvard.csl
journal: Internet Interventions
output: 
  rticles::elsevier_article:
    keep_tex: true
    latex_engine: pdflatex
    citation_package: default
  word_document:
    default
    #reference_docx: "2110071135_ip_m-template-instructions.docx"
#knit: (function(inputFile, encoding){rmarkdown::render(inputFile, encoding = encoding, output_format = "all") })
classoption: 3p
header-includes:
  # - \usepackage{fontspec}
  # - \setmainfont[Path=fonts/,BoldFont={texgyretermes-bold.otf},ItalicFont={texgyretermes-italic.otf},BoldItalicFont={texgyretermes-bolditalic.otf}]{texgyretermes-regular.otf}
  # - \usepackage{unicode-math}
  # - \setmathfont[Path=fonts/]{texgyretermes-math.otf}
  - \usepackage{mathptmx}
  - \usepackage[format=plain,labelsep=period,labelfont=bf,textfont=it]{caption}
  - \usepackage[nomarkers,nolists]{endfloat}
  - \usepackage[figuresright]{rotating}
  - \DeclareDelayedFloatFlavor{sidewaystable}{table}
  - \usepackage{xcolor}\definecolor{newtext}{rgb}{1,0,0}\definecolor{oldtext}{rgb}{0,0,0}
---

<!-- highlights: -->
<!--   - "Stand-alone iCBT assertiveness training is effective at increasing levels of adaptive assertiveness" -->
<!--   - "Stand-alone iCBT assertiveness training is effective at alleviating symptoms of social anxiety to the point of clinical recovery for a significant number of participants" -->
<!--   - "The effects were maintained at the one year follow-up" -->
<!--   - "The assertiveness construct is worthy of revived clinical research interest" -->

```{r setup, include=F}

# Font sources:
# - https://www.ctan.org/pkg/tex-gyre-termes
# - https://www.ctan.org/pkg/tex-gyre-math-termes

packages <-
  c(
    "pwr",
    "readxl",
    "writexl",
    "lmerTest",
    "dunn.test",
    "ggplot2",
    "tidyr",
    "jtools",
    "modelr",
    "ggeffects",
    "emmeans",
    "patchwork",
    "performance",
    "sjPlot",
    "clinicalsignificance",
    "here",
    "linebreak",
    "MOTE",
    "rticles"
  )
if (!require("install.load")) install.packages("install.load")
library(install.load)
install_load(packages)

# https://github.com/haozhu233/kableExtra/issues/750
devtools::install_github("kupietz/kableExtra")
library(kableExtra)

knitr::opts_chunk$set(
  warning = F,
  message = F,
  echo = F,
  collapse = T,
  fig.retina = 4,
  dpi = 196,
  out.width = "100%",
  fig.width = 7.5,
  fig.asp = 0.618
)

```

```{r body, child="body.Rmd", eval=TRUE}
```